### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by branpar** [jonschlinkert/gulp-htmlmin#73]
Hello,

I have experienced an issue trying to get this to work. Here is my htmlmin task:

```
var config = require('../config')

var changed = require('gulp-changed'),
    gulp = require('gulp'),
    htmlmin = require('gulp-htmlmin'),
    path = require('path');

var paths = {
  src: path.join(config.root.src, config.tasks.html.src, '/**/*.{' + config.tasks.html.extensions + '}'),
  dest: path.join(config.root.dest, config.tasks.html.dest)
}

var htmlTask = function() {
  return gulp.src(paths.src)
    .pipe(changed(paths.dest))
    .pipe(htmlmin({collapseWhitespace: true}))
    .pipe(gulp.dest(paths.dest))
}

gulp.task('html', htmlTask)
module.exports = htmlTask
```

This takes all source files in `./html/**/*.{htm,html}` and sends them to `./dist/html/**/*.{htm,html}`. The problem is, when I run this I get the following error. I'm removing the source code it prints on the screen, but basically it also prints out the entire HTML source on the console.

```
[15:17:07] Starting 'html'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: [html source code]
    at new HTMLParser (C:\WebTeam1\CDN\assets\node_modules\html-minifier\src\htmlparser.js:236:13)
    at minify (C:\WebTeam1\CDN\assets\node_modules\html-minifier\src\htmlminifier.js:954:3)
    at Object.exports.minify (C:\WebTeam1\CDN\assets\node_modules\html-minifier\src\htmlminifier.js:
1307:10)
    at objectAssign.fileName (C:\WebTeam1\CDN\assets\node_modules\gulp-htmlmin\index.js:22:39)
    at module.exports (C:\WebTeam1\CDN\assets\node_modules\tryit\tryit.js:8:9)
    at minifyHtml (C:\WebTeam1\CDN\assets\node_modules\gulp-htmlmin\index.js:21:9)
    at Transform.htmlminTransform [as _transform] (C:\WebTeam1\CDN\assets\node_modules\gulp-htmlmin\
index.js:51:7)
    at Transform._read (C:\WebTeam1\CDN\assets\node_modules\gulp-htmlmin\node_modules\readable-strea
m\lib\_stream_transform.js:159:10)
    at Transform._write (C:\WebTeam1\CDN\assets\node_modules\gulp-htmlmin\node_modules\readable-stre
am\lib\_stream_transform.js:147:83)
    at doWrite (C:\WebTeam1\CDN\assets\node_modules\gulp-htmlmin\node_modules\readable-stream\lib\_s
tream_writable.js:319:64)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "run" "production"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! site@1.0.0 production: `gulp production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the site@1.0.0 production script 'gulp production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the assets package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs assets
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls assets
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\site\assets\npm-debug.log
```

I don't see anything wrong with my implementation and the error isn't helpful. I've also tried pointing directly to only one file and it still gives this same error.

**Comment by shinnn** [comment]
Read the error message.

> Error: Parse Error: [html source code]

Some of your HTML is broken.

**Comment by shinnn** [comment]
I guess your next question is, "what's wrong with my HTML file?". However, before posting new comments, check [the already closed issues](https://github.com/jonschlinkert/gulp-htmlmin/issues?q=is%3Aissue+is%3Aclosed) and how we deal with HTML parser issues.
