### ISSUE TITLE
can not support angular html

### ISSUE THREAD

**Issue by pengyonglei** [jonschlinkert/gulp-htmlmin#76]
Is angular html unsupported ?

**Comment by shinnn** [comment]
Read at least the top of [README](https://github.com/jonschlinkert/gulp-htmlmin/tree/v3.0.0#readme) before opening new issues.

**Comment by deli6z** [comment]
there is nothing about angular support in readme file

**Comment by shinnn** [comment]
There *is*.

**Comment by AndrewIsh** [comment]
I switched from `gulp-minify-html` to this library today due to the form being deprecated. I immediately ran into problems (see below) when trying to minify my Angular templates. I looked in the README linked above and could find no reference to Angular. Are Angular view templates supported?
```
events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: <rebus-btn-slideout
                                obj="$index"
                                toggle-btn="sublistCtrl.deleteButton"
                                options-btns="sublistCtrl.deleteButtonConfirm"
                            </rebus-btn-slideout>
                            <button ng-click="sublistCtrl.deleteSublist(thisSub)" uib-tooltip="Delete this sublist" class="btn btn-danger btn-xs">
                                <i class="material-icons md-18">delete</i>
                            </button>
                        </div>
                        <div class="sublist-actions-bar btn-group pull-right" role="group">
                            <button ng-show="thisSub.suppressed" ng-click="sublistCtrl.goToBuffer(thisSub)" uib-tooltip="List suppressed - edit list" class="btn btn-default btn-xs">
                                <i class="material-icons md-18">visibility_off</i>
                            </button>
                            <div type="button" class="btn btn-default btn-xs" uib-tooltip="Re-order this sublist" ui-tree-handle>
                                <i class="material-icons md-18">open_with</i>
                            </div>
                        </div>
                        <h4><a href="/#/list/{{thisSub.id}}">{{thisSub.name}}</a></h4>
                        <p>{{thisSub.summary}}</p>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</li>

    at new HTMLParser (/home/rebus/rebus-list/node_modules/html-minifier/src/htmlparser.js:235:13)
    at minify (/home/rebus/rebus-list/node_modules/html-minifier/src/htmlminifier.js:944:3)
    at Object.exports.minify (/home/rebus/rebus-list/node_modules/html-minifier/src/htmlminifier.js:1299:10)
    at Object.assign.fileName (/home/rebus/rebus-list/node_modules/gulp-htmlmin/index.js:21:39)
    at module.exports (/home/rebus/rebus-list/node_modules/tryit/tryit.js:8:9)
    at minifyHtml (/home/rebus/rebus-list/node_modules/gulp-htmlmin/index.js:20:9)
    at Transform.htmlminTransform [as _transform] (/home/rebus/rebus-list/node_modules/gulp-htmlmin/index.js:50:7)
    at Transform._read (/home/rebus/rebus-list/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/rebus/rebus-list/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/rebus/rebus-list/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_writable.js:418:64)
```
events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: <myapp-btn-slideout
                                obj="$index"
                                toggle-btn="sublistCtrl.deleteButton"
                                options-btns="sublistCtrl.deleteButtonConfirm"
                            </myapp-btn-slideout>
                            <button ng-click="sublistCtrl.deleteSublist(thisSub)" uib-tooltip="Delete this sublist" class="btn btn-danger btn-xs">
                                <i class="material-icons md-18">delete</i>
                            </button>
                        </div>
                        <div class="sublist-actions-bar btn-group pull-right" role="group">
                            <button ng-show="thisSub.suppressed" ng-click="sublistCtrl.goToBuffer(thisSub)" uib-tooltip="List suppressed - edit list" class="btn btn-default btn-xs">
                                <i class="material-icons md-18">visibility_off</i>
                            </button>
                            <div type="button" class="btn btn-default btn-xs" uib-tooltip="Re-order this sublist" ui-tree-handle>
                                <i class="material-icons md-18">open_with</i>
                            </div>
                        </div>
                        <h4><a href="/#/list/{{thisSub.id}}">{{thisSub.name}}</a></h4>
                        <p>{{thisSub.summary}}</p>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</li>

    at new HTMLParser (/home/myapp/myapp-list/node_modules/html-minifier/src/htmlparser.js:235:13)
    at minify (/home/myapp/myapp-list/node_modules/html-minifier/src/htmlminifier.js:944:3)
    at Object.exports.minify (/home/myapp/myapp-list/node_modules/html-minifier/src/htmlminifier.js:1299:10)
    at Object.assign.fileName (/home/myapp/myapp-list/node_modules/gulp-htmlmin/index.js:21:39)
    at module.exports (/home/myapp/myapp-list/node_modules/tryit/tryit.js:8:9)
    at minifyHtml (/home/myapp/myapp-list/node_modules/gulp-htmlmin/index.js:20:9)
    at Transform.htmlminTransform [as _transform] (/home/myapp/myapp-list/node_modules/gulp-htmlmin/index.js:50:7)
    at Transform._read (/home/myapp/myapp-list/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/myapp/myapp-list/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/myapp/myapp-list/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_writable.js:418:64)
```

**Comment by shinnn** [comment]
> I looked in the README linked above

So, you missed

> *Issues with the HTML parser and output should be reported on the [html-minifier](https://github.com/kangax/html-minifier/issues) issue tracker.*
