### ISSUE TITLE
gulp-htmlmin only minifies 5 html files at once and throws an error

### ISSUE THREAD

**Issue by Codehan25** [jonschlinkert/gulp-htmlmin#97]
Hi,

I noticed that the gulp-htmlmin plugin minifies only 5 html files at once and throws an error.

Is there a specific reason for this and does the plugin handle mixed PHP code?

This is how my task is structured:

```
gulp.task ('minifyHTML', function () {
    "use strict";
    return gulp.src ('./ html_templates / *. html5')
        .pipe (htmlmin ({
            collapseWhitespace: true
        }))
        .pipe (gulp.dest ( './ templates'));
});
```

This error is displayed in the terminal after the plugin has minified 5 html5 files:

```
[01:16:23] Starting 'minifyHTML'...

events.js:136
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: <	obc4kq1kg8l5	>	obc4kq1kg8l6	</	obc4kq1kg8l7	>	obc4kq1kg8l8	<a href="	obc4kq1kg8l9	#	obc4kq1kg8l10	" class="invisible">	obc4kq1kg8l11	</a>	obc4kq1kg8l12	<a id="	obc4kq1kg8l13	" class="invisible">&nbsp;</a>

</nav>

    at new HTMLParser (/Applications/MAMP/htdocs/codehan_portfolio/node_modules/html-minifier/src/htmlparser.js:240:13)
    at minify (/Applications/MAMP/htdocs/codehan_portfolio/node_modules/html-minifier/src/htmlminifier.js:944:3)
    at Object.exports.minify (/Applications/MAMP/htdocs/codehan_portfolio/node_modules/html-minifier/src/htmlminifier.js:1304:10)
    at Object.assign.fileName (/Applications/MAMP/htdocs/codehan_portfolio/node_modules/gulp-htmlmin/index.js:21:39)
    at module.exports (/Applications/MAMP/htdocs/codehan_portfolio/node_modules/tryit/tryit.js:8:9)
    at minifyHtml (/Applications/MAMP/htdocs/codehan_portfolio/node_modules/gulp-htmlmin/index.js:20:9)
    at Transform.htmlminTransform [as _transform] (/Applications/MAMP/htdocs/codehan_portfolio/node_modules/gulp-htmlmin/index.js:50:7)
    at Transform._read (/Applications/MAMP/htdocs/codehan_portfolio/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Applications/MAMP/htdocs/codehan_portfolio/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Applications/MAMP/htdocs/codehan_portfolio/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_writable.js:428:64)
```

**Comment by doowb** [comment]
> Error: Parse Error:

This says there's a parse error, which would be coming from `html-minifier`. As the README.md suggests, you should open [an issue there](https://github.com/kangax/html-minifier/issues).

Also, check `html-minifier` docs to see if it handles PHP code.
